config/routes.rb
Rails.application.routes.draw do
    
  resources :chapters, only: [:index, :show] do
    resources :questions, only: [:show, :update] do
    end
  end
 
  resources :cliente_servicios do 
    member do
      post :bajar
      post :revivir
    end
  end

  resources :articles
  resources :categories

  resources :tickets do
    member do
      post :change_state
      post :close_state
    end
    resources :comments, only: [:create, :destroy, :update]
  end

  resources :clientes, :programs, :people, :derivations
  resources :subjects, :referents, :organizations, :pins
  resources :ipp_cases, :servicios, :images
 
  devise_for :users,
  :path => "usuarios",
  :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :unlock => 'unblock',
    :registration => 'register',
    :sign_up => 'cmon_let_me_in' }
  
  
  root 'static_pages#home'
  get '/ayuda', to: 'static_pages#ayuda'
  get '/contacto', to: 'static_pages#contacto'
    
  resources :subjects do
    resources :derivations
  end
  
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

app/models/ticket.rb
# == Schema Information
#
# Table name: tickets
#
#  id                  :integer          not null, primary key
#  title               :string
#  fecha_inicio        :datetime
#  reason              :string
#  description         :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  cliente_servicio_id :integer
#  user_id             :integer
#  aasm_state          :string
#  state               :string
#

class Ticket < ApplicationRecord
	
	belongs_to :user
	has_many :comments, dependent: :delete_all
	validates :title, :reason, :description, presence: true

	include AASM

	aasm do
		state :Pendiente, initial: true
		state :Resolviendo, :Resuelto, :Cerrado
		
		event :progress do
			transitions from: :Pendiente, to: :Resolviendo
		end

		event :solution do
			transitions from: [:Pendiente, :Resolviendo], to: :Resuelto
		end

		event :close do
			transitions from: [:Pendiente, :Resolviendo, :Resuelto], to: :Cerrado
		end
  	end

  	#scope :creados, -> { where(aasm_state: "pending" ) }
  	#scope :en_proceso, -> { where(aasm_state: "in_progress" ) }
	#scope :ultimos, -> { order("created_at DESC").limit(3) }

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :set_cliente_servicio, only: [:new]
  before_action :authenticate_user!

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.where.not(aasm_state: "Cerrado")
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @comment = Comment.new
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = current_user.tickets.new(ticket_params)
    
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket Creado.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket Actualizado.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_state
    @ticket = current_user.tickets.find(params[:id])
    if params[:tipo] == "Resolviendo"
      @ticket.progress!
    end
    if params[:tipo] == "Resuelto"
      @ticket.solution!
    end
    redirect_to tickets_path
  end

  def close_state 
    @ticket = current_user.tickets.find(params[:id])
    @ticket.close!
    redirect_to tickets_path
  end
 
  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket Eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :fecha_inicio, :aasm_state,
                     :reason, :description, :cliente_servicio_id, :user_id)
    end

    def set_cliente_servicio
      @cliente_servicio = ClienteServicio.all
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>

  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">  
        <%= form.label :cliente_servicio, 'Elegir CPA / ID' %>
        <%= form.collection_select :cliente_servicio_id, ClienteServicio.where(aasm_state:"Alta"), :cpaid, :cpaid   %>
    </div>

  <div class="field">
    <%= form.label :title, 'Título' %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :fecha_inicio, 'Fecha y Hora' %>
    <%= form.datetime_select :fecha_inicio %>
  </div>

  <div class="field">
    <%= form.label :reason, 'Motivo' %>
    <%= form.text_field :reason %>
  </div>

  <div class="field">
    <%= form.label :description, 'Descripción' %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit 'Grabar Ticket', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1 class="text-left">Sistema de Tickets</h1>
<%= link_to "Crear Nuevo Ticket", new_ticket_path, 
class: "btn btn-primary" %>
<%= link_to "Ticket Cerrados", tickets_path(aasm_state: "Cerrado"), 
class: "btn btn-warning" %><br><br>



  <div class="table-responsive">
  <table class="table table-bordered table-hover">
  <thead>
    <tr class="d-flex">
      <th>CPA / ID</th>
      <th>Título</th>
      <th>Inicio</th>
      <th>Estado</th>
      <th>Motivo</th>
      <th>Descripción</th>
      <th class="text-center">Opciones</th>
      <th class="text-center">Cambiar Estado:</th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr class="d-flex">
        <td style="vertical-align: middle;"><%= ticket.cliente_servicio_id %></td>
        <td style="width: 8%; vertical-align: middle;"><%= ticket.title %></td>
        <td style="width: 10%; vertical-align: middle;"><%= ticket.fecha_inicio %></td>
        <td style="vertical-align: middle;"><%= ticket.aasm_state %></td>
        <td style="width: 16%; vertical-align: middle;"><%= ticket.reason %></td>
        <td style="width: 20%; vertical-align: middle;"><%= ticket.description %></td>
        
        <th class="text-center" style="vertical-align: middle;">
        <%= link_to "Detalles", ticket, class: "btn btn-success"%> 
           
        <th class="text-center" style="vertical-align: middle;">
        
        <% if ticket.aasm_state == "Pendiente" %>
          <%= link_to 'En Proceso', change_state_ticket_path(ticket, tipo: "Resolviendo"),  method: :post, data: { confirm: 'Estás seguro?' }, class: "btn btn-info" %>
          <%= link_to 'Resuelto', change_state_ticket_path(ticket, tipo: "Resuelto"), 
          method: :post, data: { confirm: 'Estás seguro?' }, class: "btn btn-warning" %>  
          <%= link_to 'Cerrar', close_state_ticket_path(ticket), 
          method: :post, data: { confirm: 'Estás seguro?' }, class: "btn btn-danger" %>
        <% end %>

        <% if ticket.aasm_state == "Resolviendo" %>
          <%= link_to 'Resuelto', change_state_ticket_path(ticket, tipo: "Resuelto"), 
          method: :post, data: { confirm: 'Estás seguro?' }, class: "btn btn-warning" %>  
          <%= link_to 'Cerrar', close_state_ticket_path(ticket), 
          method: :post, data: { confirm: 'Estás seguro?' }, class: "btn btn-danger" %>
        <% end %>

        <% if ticket.aasm_state == "Resuelto" %>
          <%= link_to 'Cerrar', close_state_ticket_path(ticket), 
          method: :post, data: { confirm: 'Estás seguro?' }, class: "btn btn-danger" %>
        <% end %>

 <div class="btn-group">
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Action
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Separated link</a>
  </div>
</div>

        </th>
         </th>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<div class="container">
    <div class="formulario">
<h1>
  <strong>CPA - ID:</strong>
  <%= @ticket.cliente_servicio_id %>
</h1>

<div class="ticket-1">
<div class="table-responsive">
  <table class="table table-bordered table-hover">
  <thead>
    <tr class="d-flex">
      <th>Ticket</th>
      <th>Cliente</th>
    </tr>
  </thead>

  <tbody>
     <tr class="d-flex">
      <td>
        <p>
          <strong>Título:</strong>
          <%= @ticket.title %>
        </p>

        <p>
          <strong>Fecha & Hora de Inicio:</strong>
          <%= @ticket.fecha_inicio %>
        </p>

        <p>
          <strong>Estado del Ticket:</strong>
          <%= @ticket.aasm_state %>
        </p>

        <p>
          <strong>Motivo:</strong>
          <%= @ticket.reason %>
        </p>

        <p>
          <strong>Descripción:</strong>
          <%= @ticket.description %>
        </p>
      </td>
      <td>
        <strong>Título:</strong>
          <%= @ticket.title %>
        </p>

        <p>
          <strong>Fecha & Hora de Inicio:</strong>
          <%= @ticket.fecha_inicio %>
        </p>

        <p>
          <strong>Estado del Ticket:</strong>
          <%= @ticket.aasm_state %>
        </p>

        <p>
          <strong>Motivo:</strong>
          <%= @ticket.reason %>
        </p>

        <p>
          <strong>Descripción:</strong>
          <%= @ticket.description %>
        </p>
      </td>
    </tr>
  </tbody>
</table>
</div>
</div>


<p>
   <strong>Comentario Nuevo:</strong>
  <%= render 'comments/form' %>
  <ul>
    <% @ticket.comments.each do |c| %>
      <li>
        <%= c.body %> - <%= c.user.email %>
      </li>
    <% end %>
  </ul>  
</p>



<%= link_to 'Editar Ticket', edit_ticket_path(@ticket), class: "btn btn-primary"  %> 
<%= link_to 'Listado de Tickets', tickets_path, class: "btn btn-warning"  %>

</div>
</div>