config/routes.rb
Rails.application.routes.draw do
    
  resources :chapters, only: [:index, :show] do
    resources :questions, only: [:show, :update] do
    end
  end
 
  resources :cliente_servicios do 
    member do
      post :bajar
      post :revivir
    end
  end

  resources :articles
  resources :categories

  resources :tickets do
    member do
      post :change_state
      post :close_state
    end
    resources :comments, only: [:create, :destroy, :update]
  end

  resources :clientes, :programs, :people, :derivations
  resources :subjects, :referents, :organizations, :pins
  resources :ipp_cases, :servicios, :images
 
  devise_for :users,
  :path => "usuarios",
  :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :unlock => 'unblock',
    :registration => 'register',
    :sign_up => 'cmon_let_me_in' }
  
  
  root 'static_pages#home'
  get '/ayuda', to: 'static_pages#ayuda'
  get '/contacto', to: 'static_pages#contacto'
    
  resources :subjects do
    resources :derivations
  end
  
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

app/models/cliente_servicio.rb
# == Schema Information
#
# Table name: cliente_servicios
#
#  id          :integer          not null, primary key
#  fecha_alta  :datetime
#  fecha_baja  :datetime
#  aasm_state  :string
#  motivo      :string
#  direccion   :string
#  cliente_id  :integer
#  servicio_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  cpaid       :string
#

class ClienteServicio < ApplicationRecord
  belongs_to :cliente
  belongs_to :servicio
  
  include AASM

	aasm do

		state :Alta, initial: true
		state :Baja
		
		event :bajar do
			transitions from: :Alta, to: :Baja
		end

		event :revivir do
			transitions from: :Baja, to: :Alta
		end
   
  	end
end

app/controllers/cliente_servicios_controller.rb
class ClienteServiciosController < ApplicationController
  before_action :set_cliente_servicio, only: [:show, :edit, :update, :destroy, :bajar, :revivir]
  before_action :set_estado, only: [:index, :new]
  before_action :authenticate_user!

  # GET /cliente_servicios
  # GET /cliente_servicios.json
  def index
    @cliente_servicios = ClienteServicio.where aasm_state: @estado
  end

  # GET /cliente_servicios/1
  # GET /cliente_servicios/1.json
  def show
  end

  # GET /cliente_servicios/new
  def new
    @cliente_servicio = ClienteServicio.new
  end

  # GET /cliente_servicios/1/edit
  def edit
  end

  # POST /cliente_servicios
  # POST /cliente_servicios.json
  def create
    @cliente_servicio = ClienteServicio.new(cliente_servicio_params)

    respond_to do |format|
      if @cliente_servicio.save
        format.html { redirect_to @cliente_servicio, notice: 'Cliente servicio was successfully created.' }
        format.json { render :show, status: :created, location: @cliente_servicio }
      else
        format.html { render :new }
        format.json { render json: @cliente_servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cliente_servicios/1
  # PATCH/PUT /cliente_servicios/1.json
  def update
    respond_to do |format|
      if @cliente_servicio.update(cliente_servicio_params)
        format.html { redirect_to @cliente_servicio, notice: 'Cliente servicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente_servicio }
      else
        format.html { render :edit }
        format.json { render json: @cliente_servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cliente_servicios/1
  # DELETE /cliente_servicios/1.json
  def destroy
    @cliente_servicio.destroy
    respond_to do |format|
      format.html { redirect_to cliente_servicios_url, notice: 'Cliente servicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bajar
    destino = "Baja"
    if @cliente_servicio.bajar
      @cliente_servicio.update(fecha_baja: Time.zone.now)
      flash[:notice] = "Servicio dado de baja exitosamente"
    else
      destino = "Alta"
      flash[:danger] = "Error al dar de baja el servicio"
    end
    redirect_to cliente_servicios_path(estado: destino)
  end

  def revivir
    if @cliente_servicio.revivir
      @cliente_servicio.update(fecha_baja: nil)
      flash[:notice] = "Servicio revivido con éxito"
    end
    redirect_to cliente_servicios_path(estado: "Alta")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente_servicio
      @cliente_servicio = ClienteServicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_servicio_params
      params.require(:cliente_servicio).permit(:fecha_alta, :fecha_baja, :estado, :motivo, :direccion, :cliente_id, :servicio_id)
    end

    def set_estado
      #pasamos como paramétro el estado (alta o baja)
      @estado = params[:estado]
    end

end

app/helpers/cliente_servicios_helper.rb
module ClienteServiciosHelper
end

app/views/cliente_servicios/_form.html.erb
<%= form_with(model: cliente_servicio, local: true) do |form| %>
  <% if cliente_servicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente_servicio.errors.count, "error") %> prohibited this cliente_servicio from being saved:</h2>

      <ul>
      <% cliente_servicio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha_alta %>
    <%= form.datetime_select :fecha_alta %>
  </div>

  <div class="field">
    <%= form.label :fecha_baja %>
    <%= form.datetime_select :fecha_baja %>
  </div>

  <div class="field">
    <%= form.label :aasm_state %>
    <%= form.text_field :aasm_state %>
  </div>

  <div class="field">
    <%= form.label :motivo %>
    <%= form.text_field :motivo %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion %>
  </div>

  <div class="field">
    <%= form.label :cliente_id %>
    <%= form.text_field :cliente_id %>
  </div>

  <div class="field">
    <%= form.label :servicio_id %>
    <%= form.text_field :servicio_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cliente_servicios/edit.html.erb
<h1>Editing Cliente Servicio</h1>

<%= render 'form', cliente_servicio: @cliente_servicio %>

<%= link_to 'Show', @cliente_servicio %> |
<%= link_to 'Back', cliente_servicios_path %>

app/views/cliente_servicios/index.html.erb
<% if @estado == "Alta" %>
<h1>Listado de Servicios Activos</h1>
<%= link_to "Nueva Alta de Servicio", new_cliente_servicio_path, class: "btn btn-primary" %>
<%= link_to "Ver Listado de Bajas", cliente_servicios_path(estado: "Baja"), class: "btn btn-warning" %>

<br><br>
<div class="table-responsive">
  <table class="table table-bordered table-hover">
  <thead>
    <tr class="d-flex">
      <th>Cliente</th>
      <th>CPA / ID</th>
      <th>Tecnología</th>
      <th>Servicio</th>
      <th class="text-center">Contención</th>
      <th class="text-center">Cuota</th>
      <th>Proveedor</th>
      <th class="text-center">Opciones</th>
    </tr>
  </thead>

  <tbody>
  <% @cliente_servicios.each do |cliente_servicio| %>
    <% if cliente_servicio.aasm_state == "Alta" %>
      <tr class="d-flex">
        <td style="width: 23%; vertical-align: middle;"><%= cliente_servicio.cliente.name %></td>
        <td style="width: 7%; vertical-align: middle;"><%= cliente_servicio.cpaid %></td>
        <td style="width: 10%; vertical-align: middle;">
        <%= cliente_servicio.servicio.technology.name %></td>
        <td style="width: 11%; vertical-align: middle;">
        <%= cliente_servicio.servicio.bajada %> / <%= cliente_servicio.servicio.subida %> kbps</td>
        <td class="text-center" style="width: 9%; vertical-align: middle;">
        <%= cliente_servicio.servicio.contencion %></td>
        <td class="text-center" style="width: 6%; vertical-align: middle;">
        <%= cliente_servicio.servicio.cuota_trafico %> GB</td>
        <td style="width: 10%; vertical-align: middle;">
        <%= cliente_servicio.servicio.provider.name %></td>
        
        
        <td class="text-center" style="vertical-align: middle;">
     <%= link_to 'Más Info', cliente_servicio, class: "btn btn-success"  %>
     <%= link_to 'Editar', edit_cliente_servicio_path(cliente_servicio), class: "btn btn-warning"  %>
     <%= link_to 'Dar de Baja', bajar_cliente_servicio_path(cliente_servicio), 
        method: :post, data: { confirm: 'Estás seguro?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<% else %>

<% if @estado == "Baja" %>


<h1>Listado de Servicios Dados de Baja</h1>

<%= link_to "Ver Listado de Altas", cliente_servicios_path(estado: "Alta"), class: "btn btn-success" %>
<br><br>

<div class="table-responsive">
  <table class="table table-bordered table-hover">
  <thead>
    <tr class="d-flex">
      <th>Cliente</th>
      <th>CPA / ID</th>
      <th>Tecnología</th>
      <th>Servicio</th>
      <th class="text-center">Contención</th>
      <th class="text-center">Cuota</th>
      <th>Proveedor</th>
      <th>Fecha de Baja</th>
      <th class="text-center">Opciones</th>
    </tr>
  </thead>

  <tbody>
  <% @cliente_servicios.each do |cliente_servicio| %>
     <% if cliente_servicio.aasm_state == "Baja" %>
      <tr class="d-flex">
        <td style="width: 18%; vertical-align: middle;"><%= cliente_servicio.cliente.name %></td>
        <td style="width: 7%; vertical-align: middle;"><%= cliente_servicio.cpaid %></td>
        <td style="width: 10%; vertical-align: middle;">
        <%= cliente_servicio.servicio.technology.name %></td>
        <td style="width: 11%; vertical-align: middle;">
        <%= cliente_servicio.servicio.bajada %> / <%= cliente_servicio.servicio.subida %> kbps</td>
        <td class="text-center" style="width: 9%; vertical-align: middle;">
        <%= cliente_servicio.servicio.contencion %></td>
        <td class="text-center" style="width: 6%; vertical-align: middle;">
        <%= cliente_servicio.servicio.cuota_trafico %> GB</td>
        <td style="width: 9%; vertical-align: middle;">
        <%= cliente_servicio.servicio.provider.name %></td>
        <td style="width: 10%; vertical-align: middle;">
        <%= cliente_servicio.fecha_baja&.strftime("%d/%m/%Y %H:%M") %></td>
        <td class="text-center" style="vertical-align: middle;">
     <%= link_to 'Más Info', cliente_servicio, class: "btn btn-success"  %>
     <%= link_to 'Editar', edit_cliente_servicio_path(cliente_servicio), class: "btn btn-warning"  %>
     <%= link_to 'Revivir', revivir_cliente_servicio_path(cliente_servicio), 
        method: :post, data: { confirm: 'Estás seguro?' }, class: "btn btn-danger" %>
      </td>
     </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<% end %>
<% end %>

app/views/cliente_servicios/new.html.erb
<h1>New Cliente Servicio</h1>

<%= render 'form', cliente_servicio: @cliente_servicio %>

<%= link_to 'Back', cliente_servicios_path %>

app/views/cliente_servicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>CPA / ID: </strong>
  <%= @cliente_servicio.cpaid %>
</p>

<p>
  <strong>Fecha alta:</strong>
  <%= @cliente_servicio.fecha_alta %>
</p>

<p>
  <strong>Fecha baja:</strong>
  <%= @cliente_servicio.fecha_baja %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @cliente_servicio.aasm_state %>
</p>

<p>
  <strong>Motivo:</strong>
  <%= @cliente_servicio.motivo %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @cliente_servicio.direccion %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @cliente_servicio.cliente.name %>
</p>

<p>
  <strong>Servicio:</strong>
  <%= @cliente_servicio.servicio.bajada %> / <%= @cliente_servicio.servicio.subida %> kbps
</p>

<%= link_to 'Edit', edit_cliente_servicio_path(@cliente_servicio) %> |
<%= link_to 'Back', cliente_servicios_path %>