config/routes.rb
Rails.application.routes.draw do
    
  resources :chapters, only: [:index, :show] do
    resources :questions, only: [:show, :update] do
    end
  end
 
  resources :cliente_servicios do 
    member do
      post :bajar
      post :revivir
    end
  end

  resources :articles
  resources :categories

  resources :tickets do
    member do
      post :change_state
      post :close_state
    end
    resources :comments, only: [:create, :destroy, :update]
  end

  resources :clientes, :programs, :people, :derivations
  resources :subjects, :referents, :organizations, :pins
  resources :ipp_cases, :servicios, :images
 
  devise_for :users,
  :path => "usuarios",
  :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :unlock => 'unblock',
    :registration => 'register',
    :sign_up => 'cmon_let_me_in' }
  
  
  root 'static_pages#home'
  get '/ayuda', to: 'static_pages#ayuda'
  get '/contacto', to: 'static_pages#contacto'
    
  resources :subjects do
    resources :derivations
  end
  
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

app/views/layouts/_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a>Monito Apps - Copyright 2019</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contacto", contacto_path %></li>
      <li><%= link_to "Ayuda", ayuda_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
   <div class="container-fluid">
    <%= link_to "MUNDO SATELITAL", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right text-uppercase">
        <li><%= link_to "Home",   root_path %></li>
        <% if user_signed_in? %>
         
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuario<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Editar Perfil", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
          </li>

      <!-- MENU DE MUNDO SATELITAL -->
      <li><%= link_to "Clientes", clientes_path %></li>
      <li><%= link_to "Tickets", tickets_path %></li>
      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Servicios<b class="caret"></b></a>
      <ul class="dropdown-menu">
         <li><%= link_to "Activos", cliente_servicios_path(:estado => "Alta") %></li>
         <li><%= link_to "Bajas", cliente_servicios_path(:estado => "Baja")   %></li>
      </ul>
      </li>
      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Precios<b class="caret"></b></a>
      <ul class="dropdown-menu">
         <% @proveedor = Provider.all %>
         <% @proveedor.each do |p| %>
         <li><%= link_to "#{p.name}", servicios_path(:provider_name=>"#{p.name}") %></li>
         <% end %>
      </ul>
      </li>

        <% else %>
        
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Registrate", new_user_registration_path %></li>

        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_ie9script.html.erb
 <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/default' %>
    <%= render 'layouts/ie9script' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%# flash.each do |key, value| %>
       <div class="alert alert-<%#= key %>"><%#= value %></div>
      <%# end %>        
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>